some bug fix when enable the EXEC_EnV_OLS
microsoft/DiskANN pull request #377
Opened 2023-06-16 02:40 UTC by jinwei14

- [X] Does this PR have a descriptive title that could go in our release notes?
- [X] Does this PR add any new dependencies?
- [X] Does this PR modify any existing APIs?
   - [X] Is the change to the API backwards compatible?
- [X] Should this result in any changes to our documentation, either updating existing docs or adding new ones?
 
#### Reference Issues/PRs

#### What does this implement/fix? Briefly explain your changes.
fixes some error when enabling EXEC_ENV_OLS 
#### Any other comments?

2023-06-18 16:41 UTC, gopalrs requested changes

2023-06-18 16:41 UTC, gopalrs commented on src/index.cpp
> +#ifndef EXEC_ENV_OLS
I assume you are not looking to have filter support in the BANN code yet?

2023-06-18 16:41 UTC, gopalrs commented on src/in_mem_data_store.cpp
> +        stream << "ERROR: Driver requests loading " << _aligned_dim << " dimension,"
This should also be "_dim"

2023-06-18 16:41 UTC, gopalrs commented on include/index.h
> +    size_t _aligned_dim;
We prefer not to have aligned dim in the index class and instead ask the datastore for it

2023-06-18 16:41 UTC, gopalrs commented on src/in_mem_data_store.cpp
> +template <typename data_t> location_t InMemDataStore<data_t>::load_impl(AlignedFileReader &reader)
The DLVS repo has the code to read an index file using an AlignedFileReader. Please check [that implementation ](https://msasg.visualstudio.com/Bing_and_IPG/_git/ObjectStore?path=/private/Pegasus/src/DssmSearch/randnsg/src/index.cpp)  for the load_impl function that takes an AlignedFileReader as argument.

As of now, this function is not loading the index.

2023-06-27 11:57 UTC, yashpatel007 commented on include/filter_utils.h
> +#ifndef _WINDOWS
Sure. Let me take a closer look.

2023-06-27 13:13 UTC, yashpatel007 commented on include/filter_utils.h
> +#ifndef _WINDOWS
I remember now, generate_label_specific_vector_files_compat() is for windows and generate_label_specific_vector_files() is for linux. Do we want to name both of them same ?

2023-06-28 07:50 UTC, gopalrs approved these changes

2023-06-28 07:50 UTC, merged